// ─── TC099 — Review Export Utilities ─────────────────────────────────────────
// Generates copy-pasteable TypeScript registry patch strings from review drafts
// so changes can be applied to the checked-in QUESTION_REVIEW_REGISTRY.

import type { ReviewDraftEntry } from './challengeReviewDraftStorage';

// ── Helpers ───────────────────────────────────────────────────────────────────

function escapeStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function indentLines(str: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return str
    .split('\n')
    .map(l => (l.trim() ? pad + l : l))
    .join('\n');
}

/** Render a single ReviewDraftEntry as a copy-pasteable registry entry string. */
export function exportDraftAsPatch(draft: ReviewDraftEntry): string {
  const lines: string[] = [];
  lines.push(`  '${escapeStr(draft.questionId)}': {`);
  lines.push(`    questionId: '${escapeStr(draft.questionId)}',`);
  lines.push(`    status: '${draft.status}',`);
  lines.push(`    tier: '${escapeStr(draft.tier)}',`);
  lines.push(`    category: '${escapeStr(draft.category)}',`);
  lines.push(`    reason: '${escapeStr(draft.reason)}',`);
  if (draft.notes) {
    lines.push(`    notes: '${escapeStr(draft.notes)}',`);
  }
  if (draft.status === 'overridden' && draft.replacementQuestionJson) {
    try {
      const parsed = JSON.parse(draft.replacementQuestionJson);
      const prettyJson = JSON.stringify(parsed, null, 6);
      // Indent the JSON block inside the replacementQuestion field
      const indented = indentLines(prettyJson, 4);
      lines.push(`    replacementQuestion: ${indented},`);
    } catch {
      lines.push(`    // replacementQuestion: (invalid JSON — fix before applying)`);
    }
  }
  lines.push(`  },`);
  return lines.join('\n');
}

/**
 * Render all drafts as a full QUESTION_REVIEW_REGISTRY_PATCH const declaration.
 * Paste this into challengeQuestionReviewRegistry.ts and spread into the registry.
 */
export function exportAllDraftsAsPatch(
  drafts: Record<string, ReviewDraftEntry>,
): string {
  const entries = Object.values(drafts);
  if (entries.length === 0) {
    return '// No drafts to export yet.';
  }

  const body = entries.map(d => exportDraftAsPatch(d)).join('\n\n');
  return [
    '// ── Paste into QUESTION_REVIEW_REGISTRY in challengeQuestionReviewRegistry.ts ──',
    '// Generated by ChallengeReviewScreen — TC099',
    '',
    'export const QUESTION_REVIEW_REGISTRY_PATCH = {',
    body,
    '};',
  ].join('\n');
}

/** Render a single draft as a minimal one-entry patch ready to paste inline. */
export function exportSingleDraftSnippet(draft: ReviewDraftEntry): string {
  return [
    '// ── Add this entry to QUESTION_REVIEW_REGISTRY ──',
    '{',
    exportDraftAsPatch(draft),
    '}',
  ].join('\n');
}
