// ─── Challenge pools by difficulty tier (TC051/TC053) ─────────────────────────
// Beginner: Lvl 1–3  |  Easy: Lvl 4–6  |  Intermediate: Lvl 7–12
// Advanced: Lvl 13–18  |  Expert: Lvl 19–25

import type { Challenge } from './challengeTypes';

// ── Beginner pool (20 challenges — Levels 1–3) ────────────────────────────────
export const BEGINNER_POOL: Challenge[] = [
  // b01–b20
  {
    id: 'b01',
    question: 'UTG open with AKo. Should you raise?',
    heroHand: ['A♠', 'K♣'],
    villainHand: ['Q♦', 'Q♣'],
    correctAnswer: 'yes',
    explanation: 'AKo is a premium hand — raise from any position. It dominates most continuing ranges and plays well post-flop.',
    runout: ['A♦', '7♥', '2♣', 'J♠', '4♦'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['UTG', 'open-raise', 'premium', 'offsuit'],
  },
  {
    id: 'b02',
    question: 'You have AA on the BTN. There is a UTG raise. 3-bet?',
    heroHand: ['A♥', 'A♣'],
    villainHand: ['K♦', 'K♥'],
    correctAnswer: 'yes',
    explanation: 'Pocket aces are the best hand in Hold\'em. Always 3-bet for value — you want to build a big pot and deny equity.',
    runout: ['A♦', '5♦', '9♣', '2♠', '7♥'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['BTN', '3-bet', 'premium'],
  },
  {
    id: 'b03',
    question: 'CO open with QQ. Should you raise?',
    heroHand: ['Q♥', 'Q♦'],
    villainHand: ['J♠', 'J♣'],
    correctAnswer: 'yes',
    explanation: 'QQ is the third-best hand in poker. Open raising from CO is standard — never limp with this hand.',
    runout: ['Q♠', '3♦', '8♥', 'K♣', '2♦'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['CO', 'open-raise', 'premium'],
  },
  {
    id: 'b04',
    question: 'On the BTN with 72o facing a UTG raise. Call?',
    heroHand: ['7♦', '2♣'],
    villainHand: ['A♣', 'K♠'],
    correctAnswer: 'no',
    explanation: '72o is the weakest hand in Hold\'em. You have almost no equity or playability — fold every time regardless of position.',
    runout: ['7♠', '7♥', '2♦', 'K♦', 'A♠'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['BTN', 'fold', 'offsuit'],
  },
  {
    id: 'b05',
    question: 'UTG raises, you have KK in the BB. 3-bet?',
    heroHand: ['K♠', 'K♥'],
    villainHand: ['J♦', 'J♣'],
    correctAnswer: 'yes',
    explanation: 'Kings are the second-best hand. Always 3-bet KK for value — flat calling in the BB lets the raiser play well post-flop.',
    runout: ['K♦', '5♣', '9♥', '2♦', '7♠'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['BB', '3-bet', 'premium'],
  },
  {
    id: 'b06',
    question: 'MP open with 83o. Should you raise?',
    heroHand: ['8♦', '3♣'],
    villainHand: ['A♠', 'Q♦'],
    correctAnswer: 'no',
    explanation: '83o is a trash hand from any position. It has poor equity against a typical calling range and no real redraw potential.',
    runout: ['8♠', '3♦', 'K♣', 'Q♥', '5♦'],
    heroWins: false,
    difficulty: 'beginner',
    tags: ['MP', 'fold', 'offsuit'],
  },
  {
    id: 'b07',
    question: 'You have AKs on the BTN. Should you open raise?',
    heroHand: ['A♦', 'K♦'],
    villainHand: ['Q♠', 'J♥'],
    correctAnswer: 'yes',
    explanation: 'AKs is the top non-pair hand in poker. It is a mandatory open raise from any position — suited makes it even stronger.',
    runout: ['A♣', 'T♦', '6♦', '2♣', 'J♦'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['BTN', 'open-raise', 'premium', 'suited'],
  },
  {
    id: 'b08',
    question: 'You have T2o in the SB facing a BTN open. Call?',
    heroHand: ['T♠', '2♦'],
    villainHand: ['K♥', '9♣'],
    correctAnswer: 'no',
    explanation: 'T2o is a very weak hand out of position. You will rarely flop anything useful and will be the worst hand in most pots.',
    runout: ['T♦', '2♣', '7♠', 'A♥', 'Q♦'],
    heroWins: false,
    difficulty: 'beginner',
    tags: ['SB', 'fold', 'offsuit'],
  },
  {
    id: 'b09',
    question: 'CO open with JJ. Should you raise?',
    heroHand: ['J♠', 'J♦'],
    villainHand: ['A♣', 'Q♥'],
    correctAnswer: 'yes',
    explanation: 'JJ is a premium pair and a standard open raise. You want to build a pot and be the aggressor going to the flop.',
    runout: ['J♣', '4♦', '8♠', '2♥', '6♦'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['CO', 'open-raise', 'premium'],
  },
  {
    id: 'b10',
    question: 'You are in the BB with 95o. UTG raises, everyone folds. Should you call?',
    heroHand: ['9♣', '5♦'],
    villainHand: ['A♠', 'K♦'],
    correctAnswer: 'no',
    explanation: '95o is too weak to call a UTG open from the BB. You are out of position with a hand that rarely makes strong combinations.',
    runout: ['9♦', '5♣', 'K♥', '2♠', 'J♦'],
    heroWins: false,
    difficulty: 'beginner',
    tags: ['BB', 'fold', 'offsuit'],
  },
  {
    id: 'b11',
    question: 'BTN open with AQo. Should you raise?',
    heroHand: ['A♦', 'Q♠'],
    villainHand: ['T♣', '9♣'],
    correctAnswer: 'yes',
    explanation: 'AQo is a strong broadway hand. From the BTN you have the best position at the table — this is a clear open.',
    runout: ['A♣', 'Q♣', '3♠', 'J♦', '5♥'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['BTN', 'open-raise', 'broadway', 'offsuit'],
  },
  {
    id: 'b12',
    question: 'UTG open with J4o. Should you raise?',
    heroHand: ['J♦', '4♣'],
    villainHand: ['A♠', 'K♥'],
    correctAnswer: 'no',
    explanation: 'J4o is a trash hand, especially from UTG where you have the worst table position. Fold and wait for a better spot.',
    runout: ['J♣', '4♦', '8♠', 'A♦', 'K♣'],
    heroWins: false,
    difficulty: 'beginner',
    tags: ['UTG', 'fold', 'offsuit'],
  },
  {
    id: 'b13',
    question: 'You have KK in the CO. Should you open raise?',
    heroHand: ['K♣', 'K♦'],
    villainHand: ['Q♥', 'Q♠'],
    correctAnswer: 'yes',
    explanation: 'Kings are the second-best hand. Always raise — you never want to let players in cheaply against this holding.',
    runout: ['K♠', '7♦', '3♥', 'A♣', '2♦'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['CO', 'open-raise', 'premium'],
  },
  {
    id: 'b14',
    question: 'You are on the BTN with Q3o. UTG raises. Should you call?',
    heroHand: ['Q♦', '3♠'],
    villainHand: ['A♥', 'J♦'],
    correctAnswer: 'no',
    explanation: 'Q3o does not have the strength to call a UTG open even from the BTN. The weak kicker and low card make this a clear fold.',
    runout: ['Q♣', '3♦', '8♥', 'A♦', 'J♠'],
    heroWins: false,
    difficulty: 'beginner',
    tags: ['BTN', 'fold', 'offsuit'],
  },
  {
    id: 'b15',
    question: 'SB facing a BTN open. You have AJs. Should you 3-bet?',
    heroHand: ['A♠', 'J♠'],
    villainHand: ['K♥', 'T♦'],
    correctAnswer: 'yes',
    explanation: 'AJs is a strong hand. From the SB, 3-betting turns your hand face-up as strong rather than playing it from out of position.',
    runout: ['A♦', 'J♦', '4♣', '2♠', '8♥'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['SB', '3-bet', 'suited', 'broadway'],
  },
  {
    id: 'b16',
    question: 'UTG opens. You have AA in the SB. Should you call or 3-bet?',
    heroHand: ['A♣', 'A♦'],
    villainHand: ['K♠', 'K♥'],
    correctAnswer: 'yes',
    explanation: 'Always 3-bet pocket aces preflop. Calling invites other players in cheaply and you lose value from the best hand in hold\'em.',
    runout: ['A♠', '3♦', '7♣', 'Q♥', '8♦'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['SB', '3-bet', 'premium'],
  },
  {
    id: 'b17',
    question: 'BTN open with K6o. Should you raise?',
    heroHand: ['K♦', '6♠'],
    villainHand: ['A♣', 'J♥'],
    correctAnswer: 'no',
    explanation: 'K6o has a decent high card but a very weak kicker. From the BTN it is borderline — many players fold this to keep their range clean.',
    runout: ['K♣', '6♦', '2♠', 'A♦', 'J♣'],
    heroWins: false,
    difficulty: 'beginner',
    tags: ['BTN', 'fold', 'offsuit'],
  },
  {
    id: 'b18',
    question: 'You have QQ in the BB. UTG raises. Should you 3-bet?',
    heroHand: ['Q♣', 'Q♦'],
    villainHand: ['A♥', 'K♦'],
    correctAnswer: 'yes',
    explanation: 'QQ is too strong to flat call. 3-betting from the BB denies equity, charges overcards, and builds the pot with the best hand.',
    runout: ['Q♠', '5♣', '9♦', 'K♠', '2♥'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['BB', '3-bet', 'premium'],
  },
  {
    id: 'b19',
    question: 'You are in UTG with T3o. Should you open?',
    heroHand: ['T♦', '3♣'],
    villainHand: ['A♠', 'Q♠'],
    correctAnswer: 'no',
    explanation: 'T3o is too weak to open from UTG. You are first to act with the worst position and a hand that rarely makes enough equity.',
    runout: ['T♣', '3♦', '7♦', 'A♥', 'Q♦'],
    heroWins: false,
    difficulty: 'beginner',
    tags: ['UTG', 'fold', 'offsuit'],
  },
  {
    id: 'b20',
    question: 'Facing a UTG open from the BTN with AQs. 3-bet or call?',
    heroHand: ['A♥', 'Q♥'],
    villainHand: ['K♠', 'K♦'],
    correctAnswer: 'yes',
    explanation: 'AQs is a strong 3-bet hand from BTN. You have position, nut-flush potential, and enough equity to 3-bet for value and as a blocker.',
    runout: ['Q♦', '5♥', 'T♥', '2♣', '8♥'],
    heroWins: true,
    difficulty: 'beginner',
    tags: ['BTN', '3-bet', 'suited', 'broadway'],
  },
];

// ── Easy pool (20 challenges — Levels 4–6) ───────────────────────────────────
export const EASY_POOL: Challenge[] = [
  // e01–e20
  {
    id: 'e01',
    question: 'BTN open with K9o. Should you raise?',
    heroHand: ['K♥', '9♦'],
    villainHand: ['A♣', '6♣'],
    correctAnswer: 'yes',
    explanation: 'K9o plays well from the BTN. You have good high-card strength, position throughout the hand, and a comfortable range to open here.',
    runout: ['K♣', '5♦', '2♣', 'A♦', '9♠'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['BTN', 'open-raise', 'offsuit'],
  },
  {
    id: 'e02',
    question: 'MP open with Q7o. Should you raise?',
    heroHand: ['Q♦', '7♣'],
    villainHand: ['A♠', 'K♦'],
    correctAnswer: 'no',
    explanation: 'Q7o has a weak kicker and no real connectivity. From MP you have players with position on you — fold this and wait for better.',
    runout: ['Q♠', 'Q♥', '7♦', '8♣', 'A♥'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['MP', 'fold', 'offsuit'],
  },
  {
    id: 'e03',
    question: 'UTG open with 33. Should you raise?',
    heroHand: ['3♠', '3♦'],
    villainHand: ['J♥', 'J♣'],
    correctAnswer: 'no',
    explanation: 'Small pairs like 33 play poorly from UTG. You will often be dominated and have no stack-to-pot ratio to justify set mining from early position.',
    runout: ['3♥', '8♠', 'Q♦', 'J♦', '2♣'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['UTG', 'fold', 'small-pair'],
  },
  {
    id: 'e04',
    question: 'BB vs BTN steal. Should you defend with 86s?',
    heroHand: ['8♣', '6♣'],
    villainHand: ['K♦', '9♥'],
    correctAnswer: 'yes',
    explanation: '86s is a standard BB defense vs a BTN open. Suited connectors connect well with flops and realize equity better than offsuit hands.',
    runout: ['7♣', '5♣', '2♣', 'J♦', 'A♠'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['BB', 'call', 'suited-connector'],
  },
  {
    id: 'e05',
    question: 'UTG limps, you are on the BTN with QJs. Raise?',
    heroHand: ['Q♠', 'J♠'],
    villainHand: ['A♦', '7♦'],
    correctAnswer: 'yes',
    explanation: 'Isolating a limper with QJs from BTN is strong play. You build the pot with a good hand while leveraging your position advantage.',
    runout: ['Q♦', 'T♦', '3♦', 'A♣', '5♠'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['BTN', 'open-raise', 'suited', 'broadway'],
  },
  {
    id: 'e06',
    question: 'CO open with 55. Should you raise?',
    heroHand: ['5♠', '5♦'],
    villainHand: ['A♥', 'K♣'],
    correctAnswer: 'yes',
    explanation: '55 is a playable open from the CO. You have position on most of the table, fold equity, and setmine potential against callers.',
    runout: ['5♣', '9♠', 'Q♦', '2♥', 'J♠'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['CO', 'open-raise', 'small-pair'],
  },
  {
    id: 'e07',
    question: 'SB vs BTN. Call a 3x open with 45s?',
    heroHand: ['4♠', '5♠'],
    villainHand: ['A♥', 'J♦'],
    correctAnswer: 'yes',
    explanation: '45s has solid playability from the SB vs a BTN open. The pot odds and implied odds from suited connectors justify the call.',
    runout: ['3♠', '6♠', '8♠', 'Q♦', 'J♣'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['SB', 'call', 'suited-connector'],
  },
  {
    id: 'e08',
    question: 'MP open with KJo. Should you raise?',
    heroHand: ['K♠', 'J♦'],
    villainHand: ['A♦', 'Q♠'],
    correctAnswer: 'yes',
    explanation: 'KJo is at the edge of a playable MP range. It has broadway potential and decent high-card strength for a standard open.',
    runout: ['K♦', 'J♣', '3♠', 'A♥', '8♦'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['MP', 'open-raise', 'broadway', 'offsuit'],
  },
  {
    id: 'e09',
    question: 'You are on the BTN facing a CO open with 77. Call?',
    heroHand: ['7♣', '7♦'],
    villainHand: ['A♠', 'Q♥'],
    correctAnswer: 'yes',
    explanation: '77 is a comfortable call on the BTN vs a CO open. You have position and strong setmine value against a hand that may not improve.',
    runout: ['7♠', '2♦', 'Q♣', 'A♦', 'T♠'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['BTN', 'call', 'small-pair', 'set-mining'],
  },
  {
    id: 'e10',
    question: 'HJ open with A5o. Should you raise?',
    heroHand: ['A♠', '5♣'],
    villainHand: ['K♦', 'Q♥'],
    correctAnswer: 'no',
    explanation: 'A5o lacks the playability for an HJ open. The weak kicker makes it hard to play post-flop when an ace comes — fold this from early-mid position.',
    runout: ['A♦', '5♦', '9♠', 'K♣', 'Q♦'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['MP', 'fold', 'offsuit'],
  },
  {
    id: 'e11',
    question: 'BTN open with QTo. Should you raise?',
    heroHand: ['Q♠', 'T♦'],
    villainHand: ['A♥', 'J♣'],
    correctAnswer: 'yes',
    explanation: 'QTo is a standard BTN open. The two broadway cards give it decent equity and playability, especially in position.',
    runout: ['Q♦', 'T♠', '5♥', 'A♣', '8♦'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['BTN', 'open-raise', 'broadway', 'offsuit'],
  },
  {
    id: 'e12',
    question: 'CO raises, BTN calls. Should you squeeze from BB with AKo?',
    heroHand: ['A♠', 'K♣'],
    villainHand: ['J♦', 'T♦'],
    correctAnswer: 'yes',
    explanation: 'AKo is strong enough to squeeze here. You have a premium hand, two players already in reduces their likely holding quality, and you gain fold equity.',
    runout: ['A♦', 'K♦', '3♣', '7♠', '2♥'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['BB', 'squeeze', 'premium', 'offsuit'],
  },
  {
    id: 'e13',
    question: 'UTG open with KTs. Should you raise?',
    heroHand: ['K♦', 'T♦'],
    villainHand: ['A♠', 'J♥'],
    correctAnswer: 'no',
    explanation: 'KTs is borderline from UTG. Many players fold this from early position since you will be out of position against most callers in tough spots.',
    runout: ['K♣', 'T♣', '6♦', 'A♦', 'J♦'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['UTG', 'fold', 'suited', 'broadway'],
  },
  {
    id: 'e14',
    question: 'BB vs BTN open. Call with Q9s?',
    heroHand: ['Q♣', '9♣'],
    villainHand: ['A♦', '6♦'],
    correctAnswer: 'yes',
    explanation: 'Q9s is a clear BB defend vs a BTN open. Suited hands with a face card have strong equity and connect well on many boards.',
    runout: ['Q♦', '9♦', '3♠', 'A♣', '5♦'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['BB', 'call', 'suited'],
  },
  {
    id: 'e15',
    question: 'CO raises, you have 22 on the BTN. Call?',
    heroHand: ['2♣', '2♦'],
    villainHand: ['A♥', 'K♣'],
    correctAnswer: 'yes',
    explanation: '22 is a classic set-mine on the BTN. Against a single raiser in position you have great implied odds if you hit a set on the flop.',
    runout: ['2♠', 'J♣', '8♦', 'A♦', 'K♠'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['BTN', 'call', 'small-pair', 'set-mining'],
  },
  {
    id: 'e16',
    question: 'You have A5s in the CO. Should you open raise?',
    heroHand: ['A♣', '5♣'],
    villainHand: ['K♥', 'Q♦'],
    correctAnswer: 'yes',
    explanation: 'A5s is a solid CO open. It has nut-flush potential, wheel equity, and plays well against typical big blind defending ranges.',
    runout: ['A♦', '3♣', '7♣', '2♠', 'J♥'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['CO', 'open-raise', 'suited', 'wheel-ace'],
  },
  {
    id: 'e17',
    question: 'UTG opens, MP calls. You have ATo on the BTN. Call?',
    heroHand: ['A♦', 'T♠'],
    villainHand: ['K♣', 'K♦'],
    correctAnswer: 'no',
    explanation: 'ATo in a multiway spot vs UTG and MP is a fold. You are dominated by AK/AJ, and the offsuit hand struggles to win big pots here.',
    runout: ['A♠', 'T♣', '4♦', 'K♥', '2♦'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['BTN', 'fold', 'broadway', 'offsuit'],
  },
  {
    id: 'e18',
    question: 'BTN raises, should SB 3-bet with AQo?',
    heroHand: ['A♥', 'Q♦'],
    villainHand: ['J♠', 'T♣'],
    correctAnswer: 'yes',
    explanation: 'AQo is strong enough to 3-bet from the SB vs a BTN open. You have a premium hand and want to play a big pot in position relative to the original raiser.',
    runout: ['A♣', 'Q♣', '5♠', '7♦', '2♥'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['SB', '3-bet', 'broadway', 'offsuit'],
  },
  {
    id: 'e19',
    question: 'You have 88 in the BB. CO raises. Call?',
    heroHand: ['8♠', '8♥'],
    villainHand: ['A♦', 'Q♠'],
    correctAnswer: 'yes',
    explanation: '88 is a solid BB defend. You have a pair that flops well as a set, and vs a CO open you are not facing a narrow premium range.',
    runout: ['8♦', '3♠', 'K♣', 'A♥', '5♦'],
    heroWins: true,
    difficulty: 'easy',
    tags: ['BB', 'call', 'small-pair'],
  },
  {
    id: 'e20',
    question: 'MP open with J8o. Should you raise?',
    heroHand: ['J♦', '8♣'],
    villainHand: ['A♠', 'T♥'],
    correctAnswer: 'no',
    explanation: 'J8o is too weak for a MP open. There is little value in playing a dominated hand out of position against tighter players.',
    runout: ['J♣', '8♦', '3♥', 'A♦', 'T♠'],
    heroWins: false,
    difficulty: 'easy',
    tags: ['MP', 'fold', 'offsuit'],
  },
];

// ── Intermediate pool (20 challenges — Levels 7–12) ───────────────────────────
export const INTERMEDIATE_POOL: Challenge[] = [
  // i01–i20
  {
    id: 'i01',
    question: 'HJ open, CO 3-bets. Should you fold JTs in the BB?',
    heroHand: ['J♣', 'T♣'],
    villainHand: ['A♠', 'Q♦'],
    correctAnswer: 'yes',
    explanation: 'JTs is attractive but cold-calling a 3-bet OOP vs a strong HJ/CO range is -EV. You will face bad SPRs and have no clear line post-flop.',
    runout: ['9♣', 'Q♣', '8♣', '4♦', '2♠'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['BB', 'fold', 'suited-connector'],
  },
  {
    id: 'i02',
    question: 'UTG raise, MP call. You have AJs in the CO. 3-bet?',
    heroHand: ['A♠', 'J♠'],
    villainHand: ['K♦', 'K♣'],
    correctAnswer: 'yes',
    explanation: 'AJs is a standard 3-bet from CO vs a UTG raise and MP flat. You have a strong hand, equity, and force the field to make a tough decision.',
    runout: ['A♦', '3♠', '8♦', 'K♥', '2♣'],
    heroWins: false,
    difficulty: 'intermediate',
    tags: ['CO', '3-bet', 'suited', 'broadway'],
  },
  {
    id: 'i03',
    question: 'BTN min-raise, SB 3-bets. You have T9s in the BB. Cold call?',
    heroHand: ['T♠', '9♠'],
    villainHand: ['A♥', 'A♦'],
    correctAnswer: 'no',
    explanation: 'Cold-calling a 3-bet OOP with T9s is -EV here. The SB range skews toward premiums and you will struggle to realize your equity from the BB.',
    runout: ['8♠', '7♠', '2♠', 'J♦', '3♦'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['BB', 'fold', 'suited-connector'],
  },
  {
    id: 'i04',
    question: 'SB vs BTN open. 3-bet bluff with A5s?',
    heroHand: ['A♥', '5♥'],
    villainHand: ['J♠', 'T♦'],
    correctAnswer: 'yes',
    explanation: 'A5s is a great 3-bet bluff from SB. You block premium aces, have nut-flush potential, and can make the wheel — all while being out of position.',
    runout: ['2♥', 'K♥', '9♥', '4♣', '7♦'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['SB', '3-bet', 'suited', 'wheel-ace', 'bluff'],
  },
  {
    id: 'i05',
    question: 'You open CO with AQo. UTG 3-bets. Fold?',
    heroHand: ['A♦', 'Q♠'],
    villainHand: ['A♠', 'K♣'],
    correctAnswer: 'yes',
    explanation: 'AQo vs a UTG 3-bet is a fold. UTG 3-bet ranges are tight — you are dominated by AK and behind JJ/QQ/KK that are in that range.',
    runout: ['A♥', 'Q♦', '2♣', 'T♠', '4♦'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['CO', 'fold', 'broadway', 'offsuit'],
  },
  {
    id: 'i06',
    question: 'CO opens, BTN 3-bets. Should SB cold 4-bet with TT?',
    heroHand: ['T♣', 'T♦'],
    villainHand: ['A♠', 'K♥'],
    correctAnswer: 'no',
    explanation: 'Cold 4-betting TT from SB is too thin. The CO/BTN 3-bet range has overpairs that dominate you, and you have no fold equity from the SB.',
    runout: ['T♥', '5♠', '8♠', 'Q♣', 'A♦'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['SB', 'fold', 'marginal'],
  },
  {
    id: 'i07',
    question: 'UTG open with QJo. Should you raise?',
    heroHand: ['Q♠', 'J♦'],
    villainHand: ['A♣', 'K♠'],
    correctAnswer: 'no',
    explanation: 'QJo is not strong enough to open from UTG. It frequently gets dominated by AJ+, KQ and you have no positional advantage to compensate.',
    runout: ['Q♦', 'J♣', '4♠', 'A♥', 'K♦'],
    heroWins: false,
    difficulty: 'intermediate',
    tags: ['UTG', 'fold', 'broadway', 'offsuit'],
  },
  {
    id: 'i08',
    question: 'CO open with A4s. Should you raise?',
    heroHand: ['A♦', '4♦'],
    villainHand: ['K♠', 'Q♣'],
    correctAnswer: 'yes',
    explanation: 'A4s is a solid CO open. Suited aces play well from late position — you have nut-flush potential, wheel equity, and a workable kicker.',
    runout: ['A♣', '4♣', '8♠', '2♦', 'J♥'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['CO', 'open-raise', 'suited', 'wheel-ace'],
  },
  {
    id: 'i09',
    question: 'BTN opens, BB 3-bets. You have KQo on the BTN. Call?',
    heroHand: ['K♠', 'Q♦'],
    villainHand: ['A♣', 'J♠'],
    correctAnswer: 'yes',
    explanation: 'KQo is a standard call vs a BB 3-bet from BTN. You have position, two strong high cards, and enough equity to see a flop profitably.',
    runout: ['K♦', 'Q♣', '5♠', '7♦', '2♥'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['BTN', 'call', 'broadway', 'offsuit'],
  },
  {
    id: 'i10',
    question: 'HJ open with 76s. Should you raise?',
    heroHand: ['7♣', '6♣'],
    villainHand: ['A♦', 'K♠'],
    correctAnswer: 'no',
    explanation: '76s is generally a fold from HJ. Suited connectors this low need better position to realize equity against typical calling ranges.',
    runout: ['8♣', '5♣', '2♣', 'Q♦', 'A♠'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['MP', 'fold', 'suited-connector'],
  },
  {
    id: 'i11',
    question: 'CO opens, BTN calls. Should you squeeze from BB with 99?',
    heroHand: ['9♠', '9♦'],
    villainHand: ['Q♦', 'J♣'],
    correctAnswer: 'yes',
    explanation: '99 is a strong squeeze from BB vs CO/BTN. You have a pair above most of their range, fold equity, and protection against multiway pots.',
    runout: ['9♥', '3♠', 'K♦', '2♣', '6♥'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['BB', 'squeeze', 'marginal'],
  },
  {
    id: 'i12',
    question: 'UTG raises, you have KTo on the BTN. Call?',
    heroHand: ['K♦', 'T♠'],
    villainHand: ['A♠', 'A♦'],
    correctAnswer: 'no',
    explanation: 'KTo vs a UTG open is a fold from BTN by many standards. The offsuit kicker and weak against UTG\'s tight range make this a spot to wait.',
    runout: ['K♠', 'T♣', '4♦', 'A♥', '2♠'],
    heroWins: false,
    difficulty: 'intermediate',
    tags: ['BTN', 'fold', 'broadway', 'offsuit', 'marginal'],
  },
  {
    id: 'i13',
    question: 'You are in MP with A3s. Should you open?',
    heroHand: ['A♠', '3♠'],
    villainHand: ['K♦', 'Q♣'],
    correctAnswer: 'no',
    explanation: 'A3s is borderline from MP. Wheel aces need position to play well post-flop, and from middle position you face out-of-position issues.',
    runout: ['A♦', '3♦', '9♠', 'K♣', 'Q♦'],
    heroWins: false,
    difficulty: 'intermediate',
    tags: ['MP', 'fold', 'suited', 'wheel-ace', 'marginal'],
  },
  {
    id: 'i14',
    question: 'BTN opens, SB calls. Should you 3-bet squeeze from BB with KQs?',
    heroHand: ['K♣', 'Q♣'],
    villainHand: ['A♦', '9♠'],
    correctAnswer: 'yes',
    explanation: 'KQs is a strong squeeze candidate from BB vs BTN/SB. You have two high cards, flush equity, and strong fold equity against the wide SB call range.',
    runout: ['K♠', 'Q♦', '7♣', '3♦', '2♠'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['BB', 'squeeze', 'suited', 'broadway'],
  },
  {
    id: 'i15',
    question: 'CO raises with AQs. UTG re-raises (3-bets). Call or fold?',
    heroHand: ['A♥', 'Q♥'],
    villainHand: ['A♦', 'K♠'],
    correctAnswer: 'yes',
    explanation: 'AQs is borderline but generally a call vs a UTG 3-bet given the suited nature. You have nut-flush equity and a reasonable flip vs JJ/QQ type ranges.',
    runout: ['Q♠', '5♥', 'T♥', '8♣', '3♥'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['CO', 'call', 'suited', 'broadway'],
  },
  {
    id: 'i16',
    question: 'HJ opens. You have T9s on the BTN. 3-bet or call?',
    heroHand: ['T♦', '9♦'],
    villainHand: ['A♣', 'Q♠'],
    correctAnswer: 'yes',
    explanation: 'T9s from BTN vs HJ is a call or light 3-bet. In position with a connected suited hand, you have great playability and implied odds.',
    runout: ['T♣', '9♠', '3♦', '5♥', 'J♦'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['BTN', 'call', 'suited-connector'],
  },
  {
    id: 'i17',
    question: 'You have J9o on the BTN facing a CO open. Call?',
    heroHand: ['J♠', '9♦'],
    villainHand: ['Q♣', 'Q♦'],
    correctAnswer: 'no',
    explanation: 'J9o is generally a fold facing a CO open from BTN. The offsuit nature and pair potential make this a hand that loses too often against a real range.',
    runout: ['J♦', '9♣', '3♠', 'Q♥', 'Q♠'],
    heroWins: false,
    difficulty: 'intermediate',
    tags: ['BTN', 'fold', 'offsuit', 'marginal'],
  },
  {
    id: 'i18',
    question: 'BTN opens with 66. Should you raise?',
    heroHand: ['6♠', '6♦'],
    villainHand: ['A♣', 'K♥'],
    correctAnswer: 'yes',
    explanation: '66 is a standard open from BTN. Small pairs from late position have setmine value and you can fold to resistance without much loss.',
    runout: ['6♥', '2♠', 'K♦', 'J♣', 'A♦'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['BTN', 'open-raise', 'small-pair'],
  },
  {
    id: 'i19',
    question: 'You are in HJ with KJo. Should you open raise?',
    heroHand: ['K♣', 'J♠'],
    villainHand: ['A♦', 'Q♣'],
    correctAnswer: 'yes',
    explanation: 'KJo is a comfortable HJ open. The two broadway cards give you solid equity and enough playability to justify an open from this position.',
    runout: ['K♦', 'J♦', '4♠', 'A♣', '7♥'],
    heroWins: false,
    difficulty: 'intermediate',
    tags: ['MP', 'open-raise', 'broadway', 'offsuit'],
  },
  {
    id: 'i20',
    question: 'BB vs BTN open. Cold call with A9s?',
    heroHand: ['A♣', '9♣'],
    villainHand: ['K♦', 'Q♠'],
    correctAnswer: 'yes',
    explanation: 'A9s is a strong BB defend. You have a suited ace, good top-pair potential, and can 3-bet or call depending on your range strategy.',
    runout: ['A♦', '9♠', '3♣', '7♦', '2♣'],
    heroWins: true,
    difficulty: 'intermediate',
    tags: ['BB', 'call', 'suited'],
  },
];

// ── Advanced pool (4 challenges) ────────────────────────────────────────────
export const ADVANCED_POOL: Challenge[] = [
  {
    id: 'c19',
    question: 'HJ open with KQs. BTN 3-bets. Call?',
    heroHand: ['K♠', 'Q♠'],
    villainHand: ['A♣', 'A♦'],
    correctAnswer: 'yes',
    explanation: 'KQs is a standard call vs a BTN 3-bet. It has good equity, nut-flush potential, and can flop well against a wide BTN 3-bet range.',
    runout: ['K♦', 'Q♦', '5♠', '2♦', 'A♥'],
    heroWins: false,
    difficulty: 'advanced',
    tags: ['preflop', 'call', '3-bet', 'suited-broadway'],
  },
  {
    id: 'c20',
    question: 'LJ raise, you have JJ in the BB. 3-bet or call?',
    heroHand: ['J♦', 'J♥'],
    villainHand: ['Q♠', 'Q♦'],
    correctAnswer: 'yes',
    explanation: 'JJ is strong enough to 3-bet from the BB. Calling lets LJ play easily, while 3-betting applies pressure and gains information.',
    runout: ['J♣', '3♠', '9♦', 'Q♣', '2♥'],
    heroWins: true,
    difficulty: 'advanced',
    tags: ['preflop', '3-bet', 'medium-pair'],
  },
  {
    id: 'a01',
    question: 'BTN opens, CO calls. Squeeze from BB with 77?',
    heroHand: ['7♠', '7♥'],
    villainHand: ['A♦', 'J♣'],
    correctAnswer: 'yes',
    explanation: '77 is a strong squeeze candidate from the BB — it has equity vs the wide BTN/CO range, fold equity, and multiway pots hurt small pairs.',
    runout: ['7♦', '2♠', 'K♣', 'A♥', '3♦'],
    heroWins: true,
    difficulty: 'advanced',
    tags: ['preflop', 'squeeze', 'medium-pair'],
  },
  {
    id: 'a02',
    question: 'CO 3-bets your HJ open. 4-bet bluff with A2s?',
    heroHand: ['A♣', '2♣'],
    villainHand: ['K♠', 'K♦'],
    correctAnswer: 'yes',
    explanation: 'A2s is a prime 4-bet bluff — it blocks AA/AK combos and has nut-flush equity, making your 4-bet range more balanced and less exploitable.',
    runout: ['A♦', '5♣', '9♣', 'Q♦', 'J♠'],
    heroWins: true,
    difficulty: 'advanced',
    tags: ['preflop', '4-bet', 'bluff', 'suited-ace'],
  },
];

// ── Expert pool (3 challenges) ───────────────────────────────────────────────
export const EXPERT_POOL: Challenge[] = [
  {
    id: 'x01',
    question: 'UTG shoves 15bb. Call with A9s in the BB?',
    heroHand: ['A♠', '9♠'],
    villainHand: ['Q♦', 'Q♠'],
    correctAnswer: 'yes',
    explanation: 'A9s has roughly 38% equity vs QQ. Against a 15bb UTG shove you need ~33% to call — A9s clears that bar with ace blockers and flush equity.',
    runout: ['A♦', '9♣', '3♠', 'K♣', '5♦'],
    heroWins: true,
    difficulty: 'expert',
    tags: ['preflop', 'call', 'shove', 'short-stack'],
  },
  {
    id: 'x02',
    question: 'BB vs BTN open. Should you 3-bet bluff with K5s?',
    heroHand: ['K♦', '5♦'],
    villainHand: ['T♠', '9♣'],
    correctAnswer: 'yes',
    explanation: 'K5s is a polarized 3-bet bluff from BB — it blocks KK, has nut-flush equity, and balances your value 3-bets against a wide BTN open.',
    runout: ['K♣', '3♦', '8♦', '5♥', 'J♦'],
    heroWins: true,
    difficulty: 'expert',
    tags: ['preflop', '3-bet', 'bluff', 'suited-king'],
  },
  {
    id: 'x03',
    question: 'CO 3-bets, BTN 4-bets. Should SB 5-bet shove with QQ?',
    heroHand: ['Q♣', 'Q♥'],
    villainHand: ['A♠', 'K♣'],
    correctAnswer: 'no',
    explanation: 'With CO 3-bet and BTN 4-bet already in, the BTN 4-bet range skews heavily toward AA/KK/AK. Shoving QQ into that spot is -EV — fold is correct.',
    runout: ['Q♦', '5♦', '8♣', 'A♦', 'J♣'],
    heroWins: true,
    difficulty: 'expert',
    tags: ['preflop', 'fold', '4-bet', 'medium-pair'],
  },
];
