// ─── Mock challenge data for DCR Poker Challenge (TC048) ─────────────────────

export type Challenge = {
  id: string;
  question: string;
  heroHand: [string, string];
  villainHand: [string, string];
  correctAnswer: 'yes' | 'no';
  explanation: string;
  runout: [string, string, string, string, string];
  heroWins: boolean;
};

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: 'c01',
    question: 'UTG open with AKo. Should you raise?',
    heroHand: ['A♠', 'K♣'],
    villainHand: ['Q♦', 'Q♣'],
    correctAnswer: 'yes',
    explanation: 'AKo is a premium hand and a mandatory open from any position. It dominates many calling ranges and flops very well.',
    runout: ['A♦', '7♥', '2♣', 'J♠', '4♦'],
    heroWins: true,
  },
  {
    id: 'c02',
    question: 'On the BTN facing a UTG open. Call with 72o?',
    heroHand: ['7♦', '2♣'],
    villainHand: ['A♣', 'K♠'],
    correctAnswer: 'no',
    explanation: '72o is the worst starting hand in Hold\'em. Even on the button, you have no equity edge and no implied odds to justify calling.',
    runout: ['7♠', '7♥', '2♦', 'K♦', 'A♠'],
    heroWins: true,
  },
  {
    id: 'c03',
    question: 'CO open with QQ. Should you raise?',
    heroHand: ['Q♥', 'Q♣'],
    villainHand: ['K♠', 'K♦'],
    correctAnswer: 'yes',
    explanation: 'QQ is a top-3 hand. Open raising from CO is mandatory. You can 3-bet or fold if there\'s action behind.',
    runout: ['Q♦', '8♣', '3♥', 'K♥', '2♠'],
    heroWins: true,
  },
  {
    id: 'c04',
    question: 'SB vs BTN steal. Call a 3x raise with 45s?',
    heroHand: ['4♠', '5♠'],
    villainHand: ['A♥', 'J♦'],
    correctAnswer: 'yes',
    explanation: 'Suited connectors like 45s have good playability. In the SB vs BTN you have position, implied odds, and the hand makes straights and flushes.',
    runout: ['3♠', '6♠', '8♠', 'Q♦', 'J♣'],
    heroWins: true,
  },
  {
    id: 'c05',
    question: 'UTG raises, you have KK in the BB. 3-bet?',
    heroHand: ['K♠', 'K♥'],
    villainHand: ['J♦', 'J♣'],
    correctAnswer: 'yes',
    explanation: 'KK is the second-best hand. Always 3-bet for value. Flat-calling in the BB sacrifices significant EV.',
    runout: ['K♦', '5♣', '9♥', '2♦', '7♠'],
    heroWins: true,
  },
  {
    id: 'c06',
    question: 'Facing a UTG open from BTN with 22. Should you call?',
    heroHand: ['2♠', '2♦'],
    villainHand: ['A♦', 'K♦'],
    correctAnswer: 'yes',
    explanation: 'Small pocket pairs have strong set-mining value when in position with implied odds. BTN is the best seat to realize this.',
    runout: ['2♣', '9♠', 'K♥', '4♦', 'J♠'],
    heroWins: true,
  },
  {
    id: 'c07',
    question: 'HJ open, CO 3-bet. Fold JTs in the BB?',
    heroHand: ['J♣', 'T♣'],
    villainHand: ['A♠', 'Q♦'],
    correctAnswer: 'yes',
    explanation: 'JTs is too weak to cold-4-bet and calling a 3-bet OOP against a cold HJ/CO range is marginal at best — folding is fine.',
    runout: ['9♣', 'Q♣', '8♣', '4♦', '2♠'],
    heroWins: true,
  },
  {
    id: 'c08',
    question: 'BTN vs BB. Open with K9o?',
    heroHand: ['K♥', '9♦'],
    villainHand: ['A♣', '6♣'],
    correctAnswer: 'yes',
    explanation: 'K9o is a solid BTN open. It has good high card strength and you\'re in position for the entire hand.',
    runout: ['K♣', '5♦', '2♣', 'A♦', '9♠'],
    heroWins: false,
  },
  {
    id: 'c09',
    question: 'UTG raise, MP call. You have AJs in the CO. 3-bet or fold?',
    heroHand: ['A♠', 'J♠'],
    villainHand: ['K♦', 'K♣'],
    correctAnswer: 'yes',
    explanation: 'AJs is a standard 3-bet or call hand from CO. With two players in already, 3-betting as a bluff-catcher with equity is fine.',
    runout: ['A♦', '3♠', '8♦', 'K♥', '2♣'],
    heroWins: false,
  },
  {
    id: 'c10',
    question: 'BTN min-raise, SB 3-bet. You have T9s in the BB. Cold call?',
    heroHand: ['T♠', '9♠'],
    villainHand: ['A♥', 'A♦'],
    correctAnswer: 'no',
    explanation: 'Cold-calling a 3-bet OOP with T9s against a strong BTN/SB range is -EV. The hand lacks the equity to fight for big pots from the BB.',
    runout: ['8♠', '7♠', '2♠', 'J♦', '3♦'],
    heroWins: true,
  },
  {
    id: 'c11',
    question: 'UTG opens, you have AA in the CO. 3-bet?',
    heroHand: ['A♥', 'A♣'],
    villainHand: ['K♦', 'K♥'],
    correctAnswer: 'yes',
    explanation: 'Aces are the best hand in poker. Always 3-bet AA for value. Slow-playing gives away equity and invites multiway situations.',
    runout: ['K♣', '5♠', '2♥', '9♦', 'A♦'],
    heroWins: true,
  },
  {
    id: 'c12',
    question: 'MP open with Q7o?',
    heroHand: ['Q♦', '7♣'],
    villainHand: ['A♠', 'K♦'],
    correctAnswer: 'no',
    explanation: 'Q7o has weak kicker strength and doesn\'t connect well. From MP you have positional disadvantage against the field — fold.',
    runout: ['Q♠', 'Q♥', '7♦', '8♣', 'A♥'],
    heroWins: true,
  },
  {
    id: 'c13',
    question: 'SB vs BTN. 3-bet bluff with A5s?',
    heroHand: ['A♥', '5♥'],
    villainHand: ['J♠', 'T♦'],
    correctAnswer: 'yes',
    explanation: 'A5s is an ideal 3-bet bluff from SB — it has a blocker to AA/AK, nut-flush equity, and can make the nuts.',
    runout: ['2♥', 'K♥', '9♥', '4♣', '7♦'],
    heroWins: true,
  },
  {
    id: 'c14',
    question: 'Five players see a cheap flop. You have 33. Should you open from UTG?',
    heroHand: ['3♠', '3♦'],
    villainHand: ['J♥', 'J♣'],
    correctAnswer: 'no',
    explanation: 'Small pairs play poorly from UTG against a wide calling range. Set-mining is best with position or multiway implied odds — fold UTG.',
    runout: ['3♥', '8♠', 'Q♦', 'J♦', '2♣'],
    heroWins: false,
  },
  {
    id: 'c15',
    question: 'CO open with AQo. UTG 3-bets. 4-bet or fold?',
    heroHand: ['A♦', 'Q♠'],
    villainHand: ['A♠', 'K♣'],
    correctAnswer: 'no',
    explanation: 'AQo vs a UTG 3-bet is a clear fold. UTG 3-bet range smashes AQo — it\'s dominated by AK and flips against JJ/QQ.',
    runout: ['A♥', 'Q♦', '2♣', 'T♠', '4♦'],
    heroWins: true,
  },
  {
    id: 'c16',
    question: 'BB vs BTN steal. Defend with 86s?',
    heroHand: ['8♣', '6♣'],
    villainHand: ['K♦', '9♥'],
    correctAnswer: 'yes',
    explanation: '86s is a standard BB defend vs a BTN open. Suited connectors have good playability and realize equity well.',
    runout: ['7♣', '5♣', '2♣', 'J♦', 'A♠'],
    heroWins: true,
  },
  {
    id: 'c17',
    question: 'UTG limps, you\'re on the BTN with QJs. Raise?',
    heroHand: ['Q♠', 'J♠'],
    villainHand: ['A♦', '7♦'],
    correctAnswer: 'yes',
    explanation: 'Isolating a limper with QJs from BTN is a strong play. You get position, build the pot with equity, and apply pressure.',
    runout: ['Q♦', 'T♦', '3♦', 'A♣', '5♠'],
    heroWins: false,
  },
  {
    id: 'c18',
    question: 'CO opens, BTN 3-bets. Should SB 4-bet cold with TT?',
    heroHand: ['T♣', 'T♦'],
    villainHand: ['A♠', 'K♥'],
    correctAnswer: 'no',
    explanation: 'Cold 4-betting TT from SB vs CO/BTN is too thin. Their 3-bet range is heavily weighted to hands that crush TT. Fold.',
    runout: ['T♥', '5♠', '8♠', 'Q♣', 'A♦'],
    heroWins: true,
  },
  {
    id: 'c19',
    question: 'HJ open with KQs. BTN 3-bets. Call?',
    heroHand: ['K♠', 'Q♠'],
    villainHand: ['A♣', 'A♦'],
    correctAnswer: 'yes',
    explanation: 'KQs is a standard call vs a BTN 3-bet. It has good equity, nut-flush potential, and can flop well against a wide BTN 3-bet range.',
    runout: ['K♦', 'Q♦', '5♠', '2♦', 'A♥'],
    heroWins: false,
  },
  {
    id: 'c20',
    question: 'LJ raise, you have JJ in the BB. 3-bet or call?',
    heroHand: ['J♦', 'J♥'],
    villainHand: ['Q♠', 'Q♦'],
    correctAnswer: 'yes',
    explanation: 'JJ is strong enough to 3-bet from the BB. Calling lets LJ play easily, while 3-betting applies pressure and gains information.',
    runout: ['J♣', '3♠', '9♦', 'Q♣', '2♥'],
    heroWins: true,
  },
];
