// ─── TC090.5 — Export Question Bank ──────────────────────────────────────────
// Formats generated questions as TypeScript source and writes them to disk.

import * as fs   from 'fs';
import * as path from 'path';

import type { TierKey, GeneratedQuestion } from './generatorTypes';
import { TIER_KEY_TO_CHALLENGE_TIER }      from './generatorConfig';

const EXPORT_DIR = path.resolve(
  __dirname,
  '../data/generated',
);

const TIER_VAR_NAMES: Record<TierKey, string> = {
  Beginner:   'generatedBeginnerQuestions',
  Apprentice: 'generatedApprenticeQuestions',
  Grinder:    'generatedGrinderQuestions',
  ChipLeader: 'generatedChipLeaderQuestions',
  Master:     'generatedMasterQuestions',
};

/** Serialize a single generated question to a compact object literal. */
function serializeQuestion(q: GeneratedQuestion): string {
  const lines: string[] = [];
  lines.push(`    id: ${JSON.stringify(q.id)},`);
  lines.push(`    tier: ${JSON.stringify(q.tier)},`);
  lines.push(`    tierIndex: ${q.tierIndex},`);
  lines.push(`    level: ${q.level},`);
  lines.push(`    category: ${JSON.stringify(q.category)},`);
  lines.push(`    prompt: ${JSON.stringify(q.prompt)},`);
  lines.push(`    explanation: ${JSON.stringify(q.explanation)},`);
  if (q.correctAction !== undefined) lines.push(`    correctAction: ${JSON.stringify(q.correctAction)},`);
  if (q.heroPosition !== undefined)  lines.push(`    heroPosition: ${JSON.stringify(q.heroPosition)},`);
  if (q.effectiveStackBb !== undefined) lines.push(`    effectiveStackBb: ${q.effectiveStackBb},`);
  if (q.choices !== undefined)   lines.push(`    choices: ${JSON.stringify(q.choices)},`);
  if (q.correctAnswer !== undefined) lines.push(`    correctAnswer: ${JSON.stringify(q.correctAnswer)},`);
  lines.push(`    tags: ${JSON.stringify(q.tags)},`);
  lines.push(`    difficultyScore: ${q.difficultyScore},`);
  return `  {\n${lines.join('\n')}\n  }`;
}

/** Format a full TypeScript module file for a tier's question bank. */
export function formatQuestionBankFile(
  questions: GeneratedQuestion[],
  tier: TierKey,
  seed: string,
): string {
  const varName = TIER_VAR_NAMES[tier];
  const serialized = questions.map(serializeQuestion).join(',\n');
  return (
    `// Auto-generated by TC090.5 question generator\n` +
    `// Tier: ${tier} | Seed: ${seed} | Count: ${questions.length}\n` +
    `// DO NOT EDIT MANUALLY — regenerate with: node generateQuestions.js\n\n` +
    `import type { ChallengeQuestion } from '../../challengeQuestionTypes';\n\n` +
    `export const ${varName}: ChallengeQuestion[] = [\n${serialized},\n];\n`
  );
}

/** Write the formatted question bank file for a single tier. */
export function writeTierFile(
  tier: TierKey,
  questions: GeneratedQuestion[],
  seed: string,
): void {
  if (!fs.existsSync(EXPORT_DIR)) {
    fs.mkdirSync(EXPORT_DIR, { recursive: true });
  }
  const tierName = TIER_VAR_NAMES[tier].replace('generated', '').replace('Questions', '');
  const fileName  = `generated${tierName}Questions.ts`;
  const filePath  = path.join(EXPORT_DIR, fileName);
  const content   = formatQuestionBankFile(questions, tier, seed);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`[export] Wrote ${questions.length} questions → ${filePath}`);
}
