// Spot Trainer Dataset — TC041
// Curated preflop spots with context: stack depth, prior action, hero hand, correct action, explanation.

export type SpotCategory = 'unopened' | 'vs_open' | 'short_stack';
export type Difficulty   = 'easy' | 'medium' | 'hard';

export interface Spot {
  id: string;
  category: SpotCategory;
  gameType: 'cash' | 'tournament';
  tableFormat: '6max' | '9max';
  stackDepthBb: number;
  heroPosition: string;
  villainPosition?: string;
  priorAction: string;
  heroHand: string;
  choices: string[];
  correctAction: string;
  explanation: string;
  difficulty: Difficulty;
}

export const SPOTS: Spot[] = [

  // ─── Unopened (20) ──────────────────────────────────────────────────────────

  {
    id: 'u01',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: 'AA',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'AA is the best hand in poker. Always open raise from any position at any stack depth.',
    difficulty: 'easy',
  },
  {
    id: 'u02',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: '72o',
    choices: ['Fold', 'Raise'],
    correctAction: 'Fold',
    explanation: "72o is the weakest hand in hold'em. UTG has 8 players left behind — fold every time.",
    difficulty: 'easy',
  },
  {
    id: 'u03',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: 'AKs',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'AKs is a premium hand that opens from every position. Raise and build the pot.',
    difficulty: 'easy',
  },
  {
    id: 'u04',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: 'KQo',
    choices: ['Fold', 'Raise'],
    correctAction: 'Fold',
    explanation: "KQo is marginal UTG in a 9-max game. With 8 players behind, you need a strong range. KQo doesn't make the cut — fold and wait for a better spot.",
    difficulty: 'medium',
  },
  {
    id: 'u05',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'MP',
    priorAction: 'Folds to you.',
    heroHand: 'AQo',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'AQo is a strong hand that opens cleanly from MP. Good equity against realistic calling ranges.',
    difficulty: 'easy',
  },
  {
    id: 'u06',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'MP',
    priorAction: 'Folds to you.',
    heroHand: '65s',
    choices: ['Fold', 'Raise'],
    correctAction: 'Fold',
    explanation: '65s is a speculative hand. From MP in 6-max you still have 4 players behind — the hand is too thin to open profitably here.',
    difficulty: 'medium',
  },
  {
    id: 'u07',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'CO',
    priorAction: 'Folds to you.',
    heroHand: 'AJo',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'AJo is a standard CO open. With only BTN, SB, and BB behind, your positional advantage allows wider raises.',
    difficulty: 'easy',
  },
  {
    id: 'u08',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'CO',
    priorAction: 'Folds to you.',
    heroHand: 'KTs',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'KTs has strong blockers, decent equity, and plays well in position. Clear open from CO.',
    difficulty: 'easy',
  },
  {
    id: 'u09',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'CO',
    priorAction: 'Folds to you.',
    heroHand: 'T3o',
    choices: ['Fold', 'Raise'],
    correctAction: 'Fold',
    explanation: 'T3o has no meaningful equity or playability. Fold even from the CO.',
    difficulty: 'easy',
  },
  {
    id: 'u10',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: 'KQo',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'KQo from the BTN is a standard open. In position with only the blinds behind, you raise a wide range.',
    difficulty: 'easy',
  },
  {
    id: 'u11',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: '98s',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: '98s has strong playability and great equity vs calling ranges. BTN is the widest open position — clear raise.',
    difficulty: 'easy',
  },
  {
    id: 'u12',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: 'J3o',
    choices: ['Fold', 'Raise'],
    correctAction: 'Fold',
    explanation: 'J3o has very poor connectivity and kicker issues. Even from the BTN, junk offsuit hands with large gaps should be folded.',
    difficulty: 'medium',
  },
  {
    id: 'u13',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: 'A5o',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'A5o has ace-high value and decent playability. BTN in 6-max opens very wide — A5o is comfortably in range.',
    difficulty: 'medium',
  },
  {
    id: 'u14',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: '74s',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'BTN in 6-max can open over 50% of hands. 74s has suited connectivity and strong positional/implied-odds value — it belongs in a BTN 6-max opening range.',
    difficulty: 'hard',
  },
  {
    id: 'u15',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: 'AQs',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'AQs is a premium hand that opens from every position. In 6-max, UTG only faces 5 opponents — clear open.',
    difficulty: 'easy',
  },
  {
    id: 'u16',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: 'JTo',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: "UTG in 6-max is equivalent to roughly CO in 9-max. JTo has enough playability and equity to open — it's inside a standard 6-max UTG range.",
    difficulty: 'medium',
  },
  {
    id: 'u17',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'CO',
    priorAction: 'Folds to you.',
    heroHand: 'K7s',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'K7s has strong blocker value and suits well for a CO 6-max open. Only BTN and blinds behind.',
    difficulty: 'medium',
  },
  {
    id: 'u18',
    category: 'unopened',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: 'Q9o',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'Q9o is inside a BTN 6-max opening range. The button opens very wide and Q9o provides reasonable top-pair potential.',
    difficulty: 'medium',
  },
  {
    id: 'u19',
    category: 'unopened',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'CO',
    priorAction: 'Folds to you.',
    heroHand: 'QJs',
    choices: ['Fold', 'Raise'],
    correctAction: 'Raise',
    explanation: 'QJs is a strong suited connector with good equity and playability. Clear CO open at 100bb in a tournament.',
    difficulty: 'easy',
  },
  {
    id: 'u20',
    category: 'unopened',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: '97s',
    choices: ['Fold', 'Raise'],
    correctAction: 'Fold',
    explanation: '97s from UTG in a 9-max tournament at 100bb is too thin. With 8 players behind you need premium holdings to open UTG.',
    difficulty: 'medium',
  },

  // ─── Vs Open (20) ───────────────────────────────────────────────────────────

  {
    id: 'vo01',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    villainPosition: 'CO',
    priorAction: 'CO opens to 2.5bb.',
    heroHand: 'AJs',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: '3-bet',
    explanation: 'AJs is a premium hand with blockers to AK and AA. 3-betting in position against a CO open is strong — you win the pot outright often and play a big pot with the equity advantage.',
    difficulty: 'hard',
  },
  {
    id: 'vo02',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'BTN',
    priorAction: 'BTN opens to 2.5bb. SB folds.',
    heroHand: 'K8s',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: "K8s is a solid BB defend. You get a good price and play in position vs BTN's wide range. Not strong enough to 3-bet, but too good to fold.",
    difficulty: 'medium',
  },
  {
    id: 'vo03',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'CO',
    priorAction: 'CO opens to 2.5bb. BTN folds. SB folds.',
    heroHand: '72o',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Fold',
    explanation: '72o is the worst hand in hold\'em. Even with a discount in the BB, the hand has no equity or playability against a CO opening range.',
    difficulty: 'easy',
  },
  {
    id: 'vo04',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    villainPosition: 'UTG',
    priorAction: 'UTG opens to 3bb. MP and CO fold.',
    heroHand: 'AQo',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: '3-bet',
    explanation: "AQo vs UTG is a 3-bet. You have strong equity vs UTG's range and are in position — a perfect spot to re-raise and take control of the pot.",
    difficulty: 'medium',
  },
  {
    id: 'vo05',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'CO',
    villainPosition: 'UTG',
    priorAction: 'UTG opens to 3bb. MP folds.',
    heroHand: 'KQs',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: "KQs vs UTG is best played as a call. UTG's range is strong — 3-betting risks getting 4-bet by better hands. Flat in position and realize your equity post-flop.",
    difficulty: 'hard',
  },
  {
    id: 'vo06',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'SB',
    villainPosition: 'BTN',
    priorAction: 'BTN opens to 2.5bb.',
    heroHand: 'A4s',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: '3-bet',
    explanation: "A4s is a textbook polarized 3-bet from SB vs BTN. The ace blocks AA/AK, and the low suited card gives backdoor equity. You'll be out of position post-flop, so 3-bet to collect folds rather than call and play a tricky OOP spot.",
    difficulty: 'hard',
  },
  {
    id: 'vo07',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'BTN',
    priorAction: 'BTN opens to 2.5bb. SB folds.',
    heroHand: 'QTo',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: "QTo is inside the BB defend range vs BTN. You're getting good odds, and the hand has top-pair potential. Not strong enough to 3-bet.",
    difficulty: 'medium',
  },
  {
    id: 'vo08',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'SB',
    priorAction: 'SB opens to 3bb.',
    heroHand: 'K9o',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: "K9o vs SB open is a profitable call. SB opens wide and you have position post-flop. K9o has enough top-pair equity to defend but isn't strong enough to 3-bet for value.",
    difficulty: 'medium',
  },
  {
    id: 'vo09',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    villainPosition: 'MP',
    priorAction: 'MP opens to 2.5bb. CO folds.',
    heroHand: 'AKo',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: '3-bet',
    explanation: 'AKo is the best non-pair hand. Always 3-bet in position. Build the pot, fold out dominated hands, and force tough decisions.',
    difficulty: 'easy',
  },
  {
    id: 'vo10',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'CO',
    priorAction: 'CO opens to 2.5bb. BTN folds. SB folds.',
    heroHand: 'JTs',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: "JTs is a classic flat vs CO from BB. You get a great price, the hand has multiway and draw equity. 3-betting risks getting it in bad if CO 4-bets.",
    difficulty: 'medium',
  },
  {
    id: 'vo11',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'SB',
    villainPosition: 'BTN',
    priorAction: 'BTN opens to 2.5bb.',
    heroHand: '55',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: '55 is a solid call vs BTN from SB. You have implied odds to set mine, and calling keeps the pot manageable when you miss. Flatting is simpler and profitable.',
    difficulty: 'medium',
  },
  {
    id: 'vo12',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'BTN',
    priorAction: 'BTN opens to 2.5bb. SB folds.',
    heroHand: 'QJs',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: 'QJs is a comfortable call vs BTN from BB. Great equity, strong draw potential, and a good price. Not quite strong enough to 3-bet for pure value.',
    difficulty: 'easy',
  },
  {
    id: 'vo13',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    villainPosition: 'UTG',
    priorAction: 'UTG opens to 3bb. MP and CO fold.',
    heroHand: 'A5s',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: '3-bet',
    explanation: 'A5s is a textbook polarized 3-bet vs UTG from BTN. It blocks AA/AK, the low suited card gives backdoor equity, and you represent a strong range while having nut-blocker value.',
    difficulty: 'hard',
  },
  {
    id: 'vo14',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'CO',
    villainPosition: 'UTG',
    priorAction: 'UTG opens to 3bb. MP folds.',
    heroHand: '98s',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Fold',
    explanation: "98s vs UTG from CO is too thin. UTG's range is strong and you'd be out of position post-flop with a speculative hand that needs to improve. Fold.",
    difficulty: 'medium',
  },
  {
    id: 'vo15',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'CO',
    priorAction: 'CO opens to 2.5bb. BTN folds. SB folds.',
    heroHand: 'AA',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: '3-bet',
    explanation: 'AA is always a 3-bet. Build the pot and get value from calls and 4-bets. Never slowplay AA preflop.',
    difficulty: 'easy',
  },
  {
    id: 'vo16',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    villainPosition: 'UTG',
    priorAction: 'UTG opens to 3bb. MP and CO fold.',
    heroHand: 'KQo',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: "KQo from BTN vs UTG is a call. UTG has a strong range, so 3-betting is thin and gets risky against a 4-bet. Flat in position and play the flop.",
    difficulty: 'medium',
  },
  {
    id: 'vo17',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'CO',
    priorAction: 'CO opens to 2.5bb. BTN folds. SB folds.',
    heroHand: 'A9o',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: "A9o vs CO from BB is a standard call. Good equity vs CO's wide range and a price worth defending. Not strong enough to 3-bet for value.",
    difficulty: 'medium',
  },
  {
    id: 'vo18',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'SB',
    villainPosition: 'BTN',
    priorAction: 'BTN opens to 2.5bb.',
    heroHand: 'K5s',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: '3-bet',
    explanation: "K5s is a good polar 3-bet from SB vs BTN. The king blocker is valuable against BTN's wide range, and you often take down the pot with a squeeze. Calling OOP with a speculative hand is worse.",
    difficulty: 'hard',
  },
  {
    id: 'vo19',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 100,
    heroPosition: 'BTN',
    villainPosition: 'CO',
    priorAction: 'CO opens to 2.5bb.',
    heroHand: 'TT',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: '3-bet',
    explanation: 'TT is a strong hand that benefits from building the pot and isolating CO. 3-betting in position is preferred — fold out weaker pairs and build the pot with the best hand.',
    difficulty: 'medium',
  },
  {
    id: 'vo20',
    category: 'vs_open',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 100,
    heroPosition: 'BB',
    villainPosition: 'BTN',
    priorAction: 'BTN opens to 2.5bb. SB folds.',
    heroHand: '43s',
    choices: ['Fold', 'Call', '3-bet'],
    correctAction: 'Call',
    explanation: '43s is a profitable BB defend vs BTN at 100bb. You get a discounted price, have implied odds, and great draw potential. Small suited connectors defend the BB well.',
    difficulty: 'hard',
  },

  // ─── Short Stack (15) ───────────────────────────────────────────────────────

  {
    id: 'ss01',
    category: 'short_stack',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 10,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: 'ATo',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: 'ATo with 10bb from BTN is a standard shove. Stack is too short for a standard open/fold line — push your full range of profitable hands.',
    difficulty: 'easy',
  },
  {
    id: 'ss02',
    category: 'short_stack',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 12,
    heroPosition: 'SB',
    priorAction: 'Folds to you.',
    heroHand: 'K9o',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: "K9o from SB at 12bb is a shove. You're heads-up vs the BB and have a reasonable hand — push your edge.",
    difficulty: 'easy',
  },
  {
    id: 'ss03',
    category: 'short_stack',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 8,
    heroPosition: 'CO',
    priorAction: 'Folds to you.',
    heroHand: '55',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: '55 at 8bb from CO is well within shove/fold range. A pair has great equity vs any calling range and fold equity on top.',
    difficulty: 'easy',
  },
  {
    id: 'ss04',
    category: 'short_stack',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 15,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: '87s',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: "87s at 15bb from BTN has good equity vs calling ranges and fold equity. It's in the profitable shove range from BTN — shoving is better than raising and leaving an awkward stack.",
    difficulty: 'medium',
  },
  {
    id: 'ss05',
    category: 'short_stack',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 10,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: 'KJo',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: 'KJo at 10bb from UTG gets called rarely enough to be profitable. Shoving is correct — strong enough equity when called, plus fold equity.',
    difficulty: 'easy',
  },
  {
    id: 'ss06',
    category: 'short_stack',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 10,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: '72o',
    choices: ['Fold', 'Shove'],
    correctAction: 'Fold',
    explanation: "72o has terrible equity when called and no blockers. Even at 10bb from BTN, 72o doesn't make the profitable shove range.",
    difficulty: 'easy',
  },
  {
    id: 'ss07',
    category: 'short_stack',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 8,
    heroPosition: 'SB',
    priorAction: 'Folds to you.',
    heroHand: 'Q6o',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: "Q6o from SB vs BB at 8bb is a profitable shove. You're heads-up against one opponent, have a queen blocker, and at 8bb your fold equity is high.",
    difficulty: 'hard',
  },
  {
    id: 'ss08',
    category: 'short_stack',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 12,
    heroPosition: 'CO',
    priorAction: 'Folds to you.',
    heroHand: 'A8o',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: 'A8o at 12bb from CO is a clear shove. Ace-high with a decent kicker at this stack depth plays well as a push/fold hand.',
    difficulty: 'easy',
  },
  {
    id: 'ss09',
    category: 'short_stack',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 15,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: 'AJs',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: 'AJs at 15bb from BTN is an easy shove. Premium hand with blockers — always jam here to deny equity and pick up the pot or go in a big favorite.',
    difficulty: 'easy',
  },
  {
    id: 'ss10',
    category: 'short_stack',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 10,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: '54s',
    choices: ['Fold', 'Shove'],
    correctAction: 'Fold',
    explanation: '54s from UTG at 10bb is a fold. You have 8 callers behind, and a low suited connector has poor equity against the strong hands that call from UTG.',
    difficulty: 'medium',
  },
  {
    id: 'ss11',
    category: 'short_stack',
    gameType: 'cash',
    tableFormat: '9max',
    stackDepthBb: 10,
    heroPosition: 'SB',
    priorAction: 'Folds to you.',
    heroHand: 'J7s',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: "J7s from SB at 10bb is a shove vs the BB alone. Suited jacks are in a profitable SB vs BB shove range — decent equity when called and fold equity to generate profit.",
    difficulty: 'hard',
  },
  {
    id: 'ss12',
    category: 'short_stack',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 15,
    heroPosition: 'CO',
    priorAction: 'Folds to you.',
    heroHand: 'KQo',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: 'KQo at 15bb from CO is a standard shove. Strong hand, good blockers, and at 15bb a 3x open commits nearly half your stack anyway — shoving is cleaner.',
    difficulty: 'easy',
  },
  {
    id: 'ss13',
    category: 'short_stack',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 20,
    heroPosition: 'BTN',
    priorAction: 'Folds to you.',
    heroHand: 'TT',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: 'TT at 20bb from BTN should be shoved. Raising to 3x leaves an awkward mid-stack — shoving is the standard play to deny equity and maximize pot odds.',
    difficulty: 'medium',
  },
  {
    id: 'ss14',
    category: 'short_stack',
    gameType: 'tournament',
    tableFormat: '9max',
    stackDepthBb: 10,
    heroPosition: 'UTG',
    priorAction: 'Folds to you.',
    heroHand: '32o',
    choices: ['Fold', 'Shove'],
    correctAction: 'Fold',
    explanation: '32o is one of the worst hands. Even at 10bb from UTG, this hand has terrible equity when called and poor blockers. Fold.',
    difficulty: 'easy',
  },
  {
    id: 'ss15',
    category: 'short_stack',
    gameType: 'cash',
    tableFormat: '6max',
    stackDepthBb: 12,
    heroPosition: 'SB',
    priorAction: 'Folds to you.',
    heroHand: 'T9o',
    choices: ['Fold', 'Shove'],
    correctAction: 'Shove',
    explanation: "T9o from SB at 12bb in 6-max is a profitable shove vs the BB. Connected holdings with reasonable equity — you're heads-up and T9o is inside the SB vs BB shove range.",
    difficulty: 'medium',
  },
];
